### PR TITLE
Switch to libplatform

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by notspiff** [comment]
This is nop except debian packaging

**Comment by notspiff** [comment]
ill merge but this is strictly nop as said earlier (was in a hurry).since kodiplatform has hard deps on platform its cmake config should pull in bith include paths and the link.

**Comment by hudokkow** [comment]
I understand this could be handled another way but i'm no cmake guru and working in the blind trying to solve a win32 problem is frustrating, to say the least. I don't even own anything with windows in it.

Anyway, tested and its all green now. -> http://jenkins.kodi.tv/job/BINARY-ADDONS/platform_label=win32/196/

Do you think its worth updating debian/* to resemble https://github.com/kodi-pvr/pvr.demo/tree/master/debian namely add *.install file?

**Comment by notspiff** [comment]
no need for .install when there is only a single package generated (excluding .dbg info).

**Comment by notspiff** [comment]
i will merge but solution is not proper as earlier mentioned.

**Comment by hudokkow** [comment]
Thanks. I'll make sure to pass your concerns to opdenkamp

**Pull request merged**
