### PR TITLE
removes crackling one channel while playing, Update optcode.h

### PR DESCRIPTION
**Pull request by okhinae**
removes crackling one channel while playing

### CODE REVIEW

**Comment by notspiff** [comment]
is this a sync from somewhere?

**Comment by okhinae** [comment]
yes, from http://sourceforge.net/projects/timidity/files/TiMidity%2B%2B/TiMidity%2B%2B-2.13.2/TiMidity%2B%2B-2.13.2.tar.gz/download

**Comment by notspiff** [comment]
can you please include that in the commit message.

**Comment by notspiff** [comment]
heh, that's the title of the pull request and not the commit message.

to change the commit message;
1) in your checkout of this branch do
git commit --amend
change the commit message
2) use git push <your origin> <thisbranch> -f

**Comment by notspiff** [comment]
i do smell a github interface commit. if so, i can do this and merge manually if that's easier for you.

**Pull request closed without merging**
